# Generated by Django 4.0.1 on 2022-01-26 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='specialInfo',
            new_name='special_info',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='passengerNumber',
        ),
        migrations.AddField(
            model_name='driver',
            name='passenger_number',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
