# Generated by Django 4.0.1 on 2022-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_rename_specialinfo_driver_special_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='type',
            field=models.CharField(choices=[('Poor', 'Poor'), ('XL', 'XL'), ('PetAccept', 'PetAccept'), ('Black', 'Black')], max_length=10),
        ),
    ]
