# Generated by Django 4.0.1 on 2022-01-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='Arrive_Time',
            new_name='arrive_time',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='WantShare',
            new_name='is_sharable',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='shareFound',
            new_name='is_share_found',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='PassengersNum',
            new_name='passenger_number',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='Pick_Up_Location',
            new_name='pick_up_location',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='Special_Request',
            new_name='special_request',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='vehicleType',
            new_name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
