# Generated by Django 4.0.1 on 2022-01-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_rename_arrive_time_ride_arrive_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareRideInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
