# Generated by Django 4.0.1 on 2022-01-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_sharerideinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShareRideInfo',
            new_name='share',
        ),
    ]
