# Generated by Django 4.0.1 on 2022-01-30 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_shareinfo_delete_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
