# Generated by Django 4.0.1 on 2022-01-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_ride_arrive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Poor', 'Poor'), ('XL', 'XL'), ('PetAccept', 'PetAccept'), ('Black', 'Black')], default='', max_length=200),
        ),
    ]
